### ISSUE TITLE
v3.0.12 添加命令面板图标

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_rmv_btn#11]
预先提个 issue 记录一下

https://github.com/siyuan-note/siyuan/issues/11186

https://github.com/siyuan-note/siyuan/issues/11133

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/1fa30b99-5bd7-4cc1-843b-cea1c071aad3)

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/c0e50aea-9399-43f5-8544-d3465ff13ff8)

**Comment by zxkmm** [comment]
谢谢T佬！欢迎提出PR，只需要修改i18n就行。如果您没空的话我自己来也行

**Comment by TCOTC** [comment]
等正式版看看有没有加这个按钮再说好了
