### ISSUE TITLE
文本输入框放置到下方

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_rmv_btn#14]
我看了一下代码发现我不会改。

总之就是有文本输入框的时候，要把文本输入框放置到下方

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/aba6db10-a2aa-4d8b-bbbd-8a1783874aa6)

还有 关于 部分也要改一下：

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/7660da89-71e6-4d9e-8c12-cdb7a45f16f9)

**Comment by zxkmm** [comment]
好的

**Comment by zxkmm** [comment]
有点奇怪，即使我新添加一行重复的内容也不行
目前排除版本影响，但是等我明天清醒时候在看看
现在先回退到正常的版本

**Comment by zxkmm** [comment]
以及你的html是没问题的

**Comment by TCOTC** [comment]
@zxkmm 好像跟这个有关：https://github.com/siyuan-note/siyuan/issues/11198

**Comment by zxkmm** [comment]
诶但是为啥我在旧版本思源排版也不正常0.o

**Comment by TCOTC** [comment]
我猜是更新之后在工作空间修改了什么导致回到旧版也不会恢复

**Comment by zxkmm** [comment]
0.o 那边讨论太复杂了我看不懂🫣

**Comment by frostime** [comment]
简单来说我在这个 issue 当中提出增加一个参数，允许让自定义的 element 像 textarea 那样独立成一行，而不是和 title description 并列。https://github.com/siyuan-note/siyuan/issues/11183

但是没想到 V 姐实现之后，把 textarea 的默认行为给改了，现在必须要通过指定 direction: "row" 才能变成和原来那样；否则就和普通的 input box 一样和 title description 放在同一行里。

我现在正在 argue V 姐要求把 textarea 的默认行为改回去。

**Comment by zxkmm** [comment]
啊啊感谢F佬解答！🙏❤️

**Comment by zxkmm** [comment]
感谢F佬修复。
下个stable关闭此issue

**Comment by TCOTC** [comment]
我感觉可以现在就关了直接发 1.1.7

**Comment by zxkmm** [comment]
没有，是F佬在思源那边修复了
这边不用动，所以我把我之前回退的又回退了，所以你的更改就完成了，其他的也不用动

**Comment by TCOTC** [comment]
我看到那个 PR 了，刚刚确认 v3.0.13-dev1 已经修好了

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/a06773dd-9187-4e65-8c83-85cbded2d22c)

**Comment by zxkmm** [comment]
我现在发新版

**Comment by TCOTC** [comment]
把预发行改一下就行了

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/ce9974ab-06c7-44d9-87b5-ebf74f81a78c)

**Comment by zxkmm** [comment]
谢谢，你来弄吧

**Comment by TCOTC** [comment]
OK 了

**Comment by zxkmm** [comment]
你有权限的，我在手机上操作有点麻烦

**Comment by zxkmm** [comment]
好的，谢谢
