### ISSUE TITLE
Lost config after update (No uninstall handler for plugin system)

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_rmv_btn#2]
更新之后配置不显示了，但在 `data\storage\petal\siyuan_rmv_btn` 路径下还能找到3个文件存着配置。

按照一闪而过的蓝色提示（才看两行字提示就没了）重装了之后， `data\storage\petal\siyuan_rmv_btn` 路径下原本那三个配置文件也消失了。

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/953a9722-20c6-4aa5-a400-56f53a2cd0e5)

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/39a663c7-d09f-4f6e-9840-491165690b95)

**Comment by zxkmm** [comment]
是的，抱歉，1.0.0版本重构了一次配置保存方式，原先的配置就失效了。建议卸载后重装一遍，以保证删除之前遗留的配置文件。如果想找回之前的配置，可以在卸载之前到``工作空间/data/storage/petal/siyuan_rmv_btn ``目录底下读取三个没有扩展名的文本文件。新的配置以json储存在同一目录。

**Comment by TCOTC** [comment]
那三个文件在我重装插件之后就消失了，可能别人也会这样

**Comment by zxkmm** [comment]
> 那三个文件在我重装插件之后就消失了，可能别人也会这样

谢谢提醒！我把删除配置写在onUnload这个handler里面，可能说思源更新插件会调用这个handler？有点奇怪。我昨天测试时候好像还挺正常的

**Comment by zxkmm** [comment]
刚去看了一下 https://github.com/siyuan-note/siyuan/blob/171b91513423811cf1eedc827cf48e3a28c293b6/app/src/plugin/index.ts#L77 思源暂时没有提供卸载插件的handler, 所以为了保证旧的残留被删干净，现阶段可能只能这样写了。不过最新的那个json配置文件应该不管怎样操作都不会被删掉的。

**Comment by zxkmm** [comment]
Should be fixed in https://github.com/zxkmm/siyuan_rmv_btn/pull/5

**Comment by TCOTC** [comment]
如果没其他问题的话，这个issue应该可以关闭了

**Comment by zxkmm** [comment]
谢谢，已关闭
