### ISSUE TITLE
要隐藏的侧栏按钮包含 tag 时，文档内的标签也会被隐藏

### ISSUE THREAD

**Issue by TCOTC** [zxkmm/siyuan_rmv_btn#3]
要隐藏的侧栏按钮包含 `tag` 时，文档内的标签也会被隐藏。

重现步骤：

1. 新建一个工作空间
2. 新建一个文档，在文档内创建标签
3. 下载并启用插件，在插件设置「要隐藏的侧栏按钮」中填写：tag ，然后保存设置
4. 现在发现刚才创建的标签被隐藏了
5. 此时禁用插件，发现刚才创建的标签可以显示出来了
6. 再启用插件，标签仍然可以显示
7. 关闭再打开思源，发现标签又被隐藏了

经测试，使用 DOMNodeInserted 、 MutationObserver 和 MutationObserver(type hard coded) 都有这个问题。

---

设置：

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/21717674-1bf8-4716-ad52-d24c35b90c37)

打开插件前：

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/77ae4821-6ba1-42e7-9cab-2521bde29306)

打开插件后：

![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/78434827/0a3f82ff-98ae-4f50-b6cf-0bf128fb120c)

**Comment by zxkmm** [comment]
感谢反馈，❤️我下午看一下有没有办法避免这个问题

**Comment by zxkmm** [comment]
fixed at https://github.com/zxkmm/siyuan_rmv_btn/commit/e972fb760afb5fabb7193673b1baf2ea381c9caa    
请测试，感谢！

**Comment by TCOTC** [comment]
经测试，问题应该已经解决了

**Comment by zxkmm** [comment]
谢谢，那我先关闭了
