### ISSUE TITLE
是否考虑兼容Docker版思源笔记？

### ISSUE THREAD

**Issue by jiusun** [zxkmm/siyuan_rmv_btn#7]
Docker版本安装该插件后提示不兼容如下图，是否考虑解决该问题？如果是思源笔记本身不支持就当我没问。
![image](https://github.com/zxkmm/siyuan_rmv_btn/assets/44629152/54f97828-713c-4da7-8934-2069252eba3b)

**Comment by zxkmm** [comment]
您好，感谢反馈，下版本支持

**Comment by zxkmm** [comment]
您好，1.1.5 版本现已支持Docker后端

**Comment by zxkmm** [comment]
因为Docker后端版本的思源的前端脱离了Electron环境，如果使用时候出现问题可以在这里反馈。特别是Safari。

**Comment by jiusun** [comment]
😘

**Comment by zxkmm** [comment]
您好我今天看了下发现之前的版本早已经支持docker镜像了，请问您那边还是显示不兼容？

**Comment by zxkmm** [comment]
哦我看错了，sorry
