### ISSUE TITLE
可以移除移动端设置吗

### ISSUE THREAD

**Issue by MasterJobSteam** [zxkmm/siyuan_rmv_btn#8]

**Comment by zxkmm** [comment]
您具体指的是哪种情况？
1. 需要移动端和电脑端的设置分开保存
2. 操作错了，需要还原设置
3. 需要移动端不启用该插件

**Comment by MasterJobSteam** [comment]
docker启用插件，移除**设置**按钮，用移动端打开仍可以打开**设置**按钮。可以移动端不显示**设置**按钮吗

**Comment by zxkmm** [comment]
请问具体是docker和移动端的哪一个设置按钮？

**Comment by CongSec** [comment]
好像没看到有移除”设置“的选项，我移除设置的原因是用于禁止发布的导出功能，因为移动端的设置在腹部功能状态下可以进行导出（关联：https://ld246.com/article/1726496537813）
![image](https://github.com/user-attachments/assets/c3c5db65-db7b-469b-af1a-2bea9ac7682f)

![image](https://github.com/user-attachments/assets/fffa3d86-11ec-4ffb-9c47-3099d7d8ff06)

**Comment by zxkmm** [comment]
@congSjwbsz 您好。目前还没有支持这个按钮的移除。但是移除这个按钮的目的应该是防止内容被偷偷保存？
如果是基于这个目的的话，即使移除了，作用也不是很大，因为从信息安全的角度来说，如果真的有人想保存的话可以保存整个html来保存内容。即使如果用户想直接尝试导出的话也可以构造http请求或者直接从html加回这个按钮来保存，所以如果想避免被保存的话应该用一些更完善的发布渠道来处理，例如用难以OCR的手写字体加上水印来公开位图之类的（虽然还是防不住有心之人）。
这个插件不太建议作为防范用户保存信息的手段来使用，这个插件只是基于用户对简洁的需求来使用，因为当用户能看到全文时候，一切防范手段都基本是无效的。

**Comment by CongSec** [comment]
感谢你的回复，但是地铁明明可以轻轻一跨就可以绕过为什么还要设置阻拦阀门呢？我只是想我的思源笔记可以进行简单的拦截一下，希望你的插件可以成为那个简单的“阀门”

**Comment by zxkmm** [comment]
隐藏菜单项里面填
,导出,

**Comment by CongSec** [comment]
这个方法已经试过了，手机端进入发布（6808端口）之后的还是会有导出的功能，在设置-关于-导出
![image](https://github.com/user-attachments/assets/074a1cdc-a3cc-413c-8667-c53716307f82)
![image](https://github.com/user-attachments/assets/330cf7c2-e294-40ce-bb6e-2272d1cf6ef1)
![image](https://github.com/user-attachments/assets/9e2dbd4e-03f6-4c9c-a652-f8f98df4921f)

**Comment by zxkmm** [comment]
设置按钮移除后还可以滑动进入设置，滑动进入设置这个特性作为插件应该拦截不了。这个建议到思源官方仓库发个issue，要求在发布模式禁用导出选项。
